services:
  - type: web
    name: indian-home-predictor
    env: python
    region: singapore # You can change this to another region closer to your users.
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
